services:
  - type: web
    name: naijacart-api
    runtime: python
    buildCommand: pip install -r NaijaCart-backend/requirements.txt
    startCommand: gunicorn --chdir NaijaCart-backend app:app
    envVars:
      - key: NAIJACART_ALLOWED_ORIGINS
        sync: false
      - key: NAIJACART_ADMIN_EMAIL
        sync: false
      - key: NAIJACART_ADMIN_PASSWORD
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
